# Generated by Django 4.1.7 on 2023-11-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_views',
            field=models.IntegerField(default=0),
        ),
    ]
