# Generated by Django 4.1.7 on 2023-11-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_id_movie_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='uid',
            new_name='id',
        ),
    ]
