# Generated by Django 4.1.7 on 2023-11-05 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_movie_views'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='movie',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
