# Generated by Django 4.1.7 on 2023-11-05 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movie_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
